version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "spanyan-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nckomqonwuc8"
s3_prefix = "spanyan-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
